"""change owner to uploaded_by in photo

Revision ID: 5edb790b8c31
Revises: 75cc5d7b6e18
Create Date: 2024-03-28 16:33:16.683210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5edb790b8c31"
down_revision: Union[str, None] = "75cc5d7b6e18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("uploaded_by_id", sa.Integer(), nullable=True))
    op.drop_constraint("photos_owner_id_fkey", "photos", type_="foreignkey")
    op.create_foreign_key(None, "photos", "users", ["uploaded_by_id"], ["id"])
    op.drop_column("photos", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "photos", type_="foreignkey")
    op.create_foreign_key(
        "photos_owner_id_fkey", "photos", "users", ["owner_id"], ["id"]
    )
    op.drop_column("photos", "uploaded_by_id")
    # ### end Alembic commands ###
