"""init_migration

Revision ID: 65b5e70ce850
Revises: 
Create Date: 2024-03-22 16:24:26.724905

"""

from typing import Sequence, Union

import fastapi_storages
import sqlalchemy as sa
from alembic import op

from app.db.database import storage

# revision identifiers, used by Alembic.
revision: str = "65b5e70ce850"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "file",
            fastapi_storages.integrations.sqlalchemy.ImageType(storage=storage),
            nullable=True,
        ),
        sa.Column("album_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_photos_title"), "photos", ["title"], unique=False)
    op.create_table(
        "user_to_photo",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "photo_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_to_photo")
    op.drop_index(op.f("ix_photos_title"), table_name="photos")
    op.drop_table("photos")
    # ### end Alembic commands ###
