"""initial

Revision ID: 8e1bbcf49ffd
Revises: 
Create Date: 2024-04-03 11:02:08.943889

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e1bbcf49ffd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("albums", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("albums", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("albums", "is_display", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("albums", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("photos", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("photos", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "photos", "uploaded_by_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "photos", "uploaded_by_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("photos", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("photos", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("albums", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("albums", "is_display", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("albums", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("albums", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
